/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-fixed-variant": "#852400",
        "secondary-container": "#c33900",
        "tertiary-fixed": "#a5f866",
        "on-tertiary-container": "#499300",
        "background": "#28051e",
        "outline": "#9c8d93",
        "surface-container": "#37122b",
        "secondary-fixed": "#ffdbd0",
        "inverse-on-surface": "#4b233c",
        "on-tertiary-fixed": "#0b2000",
        "surface-container-low": "#320e26",
        "on-primary-fixed": "#330d27",
        "on-background": "#ffd8eb",
        "on-primary-fixed-variant": "#653854",
        "on-primary-container": "#a77290",
        "on-tertiary-fixed-variant": "#255100",
        "secondary": "#ffb59e",
        "surface-bright": "#552b45",
        "on-surface-variant": "#d3c2c9",
        "secondary-fixed-dim": "#ffb59e",
        "primary-fixed": "#ffd8eb",
        "tertiary-container": "#0a1e00",
        "on-surface": "#ffd8eb",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#f2b5d6",
        "surface-container-highest": "#502741",
        "primary-container": "#300a24",
        "on-secondary": "#5e1700",
        "surface-variant": "#502741",
        "surface-tint": "#f2b5d6",
        "error-container": "#93000a",
        "surface-dim": "#28051e",
        "error": "#ffb4ab",
        "primary": "#f2b5d6",
        "tertiary-fixed-dim": "#8adb4d",
        "inverse-surface": "#ffd8eb",
        "on-tertiary": "#183800",
        "outline-variant": "#4f4449",
        "on-primary": "#4c223c",
        "surface-container-high": "#431c36",
        "surface": "#28051e",
        "on-error": "#690005",
        "on-secondary-container": "#ffe7e0",
        "surface-container-lowest": "#220218",
        "inverse-primary": "#804f6c",
        "tertiary": "#8adb4d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "48px",
        "unit": "4px",
        "container-max": "1200px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        "mono": ["JetBrains Mono", "monospace"],
        "sans": ["Fira Sans", "sans-serif"],
        "headline-xl": ["JetBrains Mono", "monospace"],
        "code-block": ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["JetBrains Mono", "monospace"],
        "terminal-input": ["JetBrains Mono", "monospace"],
        "label-sm": ["Fira Sans", "sans-serif"],
        "body-md": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
